name: qnox_pdf_text
description: Fast text extraction from PDFs for Flutter (Android via pdfbox-android, iOS via PDFKit). Also supports URLs (download then parse).
version: 0.1.0
publisher: africa.qnox
homepage: https://github.com/laurenttandika/qnox_pdf_text
repository: https://github.com/laurenttandika/qnox_pdf_text
issue_tracker: https://github.com/laurenttandika/qnox_pdf_text/issues
topics:
  - pdf
  - text-extraction
  - plugin
  - flutter-plugin

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: africa.qnox.qnox_pdf_text
        pluginClass: QnoxPdfTextPlugin
      ios:
        pluginClass: QnoxPdfTextPlugin

# Optional: helps pub.dev platform scoring (declares supported targets)
platforms:
  android:
  ios:

# Optional: show screenshots on pub.dev (commit images to repo)
# screenshots:
#   - description: Demo app extracting from local and URL PDFs
#     path: screenshots/demo.png